/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.Vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import main.AccesoDatos.AlojamientoData;
import main.AccesoDatos.CiudadData;
import main.AccesoDatos.PaqueteData;
import main.AccesoDatos.PasajeData;
import main.entidades.Alojamiento;
import main.entidades.Ciudad;
import main.entidades.Paquete;
import main.entidades.Pasaje;

/**
 *
 * @author Joni
 */
public class PaqueteModificar extends javax.swing.JInternalFrame {
        private LocalDate fechaEntOriginal=null;
        private LocalDate fechaSalOriginal=null;
        private LocalDate fechaEnt=null;
        private LocalDate fechaSal=null;
        private int primeraVez=0;
        private int idAlojamiento=0;
        private int idCiudadOrigen=0;
        private int idCiudadDestino=0;
        private int idPasaje=0;
    /**
     * Creates new form PaqueteModificar
     */
    public PaqueteModificar() {
        initComponents();
        jPOrigen.setVisible(false);
        jPPasaje.setVisible(false);
        jPAdministrar.setVisible(false);
        refrescarListaPaquete();
    }
    private void refrescarListaPaquete(){
        jCNombre.removeAllItems();
        PaqueteData paqueteData = new PaqueteData();
        List <Paquete> listaPaquete =(List<Paquete>)paqueteData.paqueteTodo();
        
        for (Paquete paquete : listaPaquete) {
            jCNombre.addItem(paquete);
        }
    } 
    private void listarOrigen(){
        CiudadData cData =new CiudadData();
        List<Ciudad>cargarCiudad =(List<Ciudad>)cData.listarCiudad();
        jCOrigen.removeAllItems();
        
        for (Ciudad item: cargarCiudad)
            jCOrigen.addItem(item);
            
    }
    private void listarDestino(){
        CiudadData cData =new CiudadData();
        List<Ciudad>cargarCiudad =(List<Ciudad>)cData.listarCiudad();
        jCDestino.removeAllItems();
        
        for (Ciudad item: cargarCiudad)
            jCDestino.addItem(item);
            
    }
    private void listaAlojamiento(){
        jCAlojamiento.removeAllItems();
        
        AlojamientoData aData = new AlojamientoData();
        Paquete paquete = (Paquete) jCNombre.getSelectedItem();
        Ciudad ciudad = paquete.getDestino();
        List<Alojamiento> cargarListaAlojamientos = (List<Alojamiento>)aData.alojamientosPorCiudad(ciudad);
        if(cargarListaAlojamientos!=null){
            for (Alojamiento item :cargarListaAlojamientos )
            jCAlojamiento.addItem(item);
        }
    }
    private void listarPasaje(){
        jCPasaje.removeAllItems();
        
        PasajeData pasajeData = new PasajeData();
            Paquete paquete = (Paquete) jCNombre.getSelectedItem();
            Ciudad ciudad = paquete.getOrigen();
            List<Pasaje> cargarListaPasajes = (List<Pasaje>)pasajeData.pasajesActivos(ciudad.getIdCiudad());
        if(cargarListaPasajes!=null){
            for (Pasaje item :cargarListaPasajes)
            jCPasaje.addItem(item);
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/main/Vistas/Imagenes/fondoPaqueteCambio2.jpg"));
        Image img=icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g)
            {
                g.drawImage(img,0,0,getWidth(),
                    getHeight(),this);
            }
        };
        jTOrigen = new javax.swing.JTextField();
        jTDestino = new javax.swing.JTextField();
        jCNombre = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTAlojamiento = new javax.swing.JTextField();
        jTPasaje = new javax.swing.JTextField();
        jROrigen = new javax.swing.JRadioButton();
        jRAlojamiento = new javax.swing.JRadioButton();
        jRPasaje = new javax.swing.JRadioButton();
        jTNombre = new javax.swing.JTextField();
        jRNombre = new javax.swing.JRadioButton();
        jBGuardarCambios = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPModificar = new javax.swing.JPanel();
        jPOrigen = new javax.swing.JPanel();
        jCOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jCDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBModificarOrigen = new javax.swing.JButton();
        jPAdministrar = new javax.swing.JPanel();
        jCAlojamiento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jDEntrada = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDSalida = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jBModificarAlojamiento = new javax.swing.JButton();
        jPPasaje = new javax.swing.JPanel();
        jCPasaje = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jBModificarPasaje = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(693, 583));

        jPanel1.setOpaque(false);

        jDesktopPane1.setOpaque(false);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(693, 593));

        jTOrigen.setEditable(false);
        jTOrigen.setText("Origen");
        jTOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOrigenActionPerformed(evt);
            }
        });

        jTDestino.setEditable(false);
        jTDestino.setText("Destino");
        jTDestino.setPreferredSize(new java.awt.Dimension(51, 24));
        jTDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDestinoActionPerformed(evt);
            }
        });

        jCNombre.setBackground(new java.awt.Color(209, 237, 251));
        jCNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCNombreMouseEntered(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(209, 237, 251));
        jButton1.setText("Buscar Paquete Asosiado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTAlojamiento.setEditable(false);
        jTAlojamiento.setText("Alojamiento");

        jTPasaje.setEditable(false);
        jTPasaje.setText("Pasaje");

        buttonGroup1.add(jROrigen);
        jROrigen.setText("Modificar");
        jROrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jROrigenActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRAlojamiento);
        jRAlojamiento.setText("Modifiicar");
        jRAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAlojamientoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRPasaje);
        jRPasaje.setText("Modificar");
        jRPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRPasajeActionPerformed(evt);
            }
        });

        jTNombre.setEditable(false);
        jTNombre.setText("Nombre");
        jTNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTNombreMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRNombre);
        jRNombre.setText("Modificar");
        jRNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNombreActionPerformed(evt);
            }
        });

        jBGuardarCambios.setBackground(new java.awt.Color(209, 237, 251));
        jBGuardarCambios.setText("Guardar Cambios");
        jBGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarCambiosActionPerformed(evt);
            }
        });

        jBBorrar.setBackground(new java.awt.Color(209, 237, 251));
        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBSalir.setBackground(new java.awt.Color(209, 237, 251));
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Paquete >");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Cambios");

        jPModificar.setOpaque(false);
        jPModificar.setPreferredSize(new java.awt.Dimension(679, 333));

        jPOrigen.setOpaque(false);
        jPOrigen.setPreferredSize(new java.awt.Dimension(679, 333));
        jPOrigen.setRequestFocusEnabled(false);

        jCOrigen.setBackground(new java.awt.Color(209, 237, 251));

        jLabel1.setText("Origen");

        jCDestino.setBackground(new java.awt.Color(209, 237, 251));

        jLabel2.setText("Destino");

        jBModificarOrigen.setBackground(new java.awt.Color(209, 237, 251));
        jBModificarOrigen.setFont(new java.awt.Font("Sitka Heading", 1, 12)); // NOI18N
        jBModificarOrigen.setForeground(new java.awt.Color(0, 0, 0));
        jBModificarOrigen.setText("Modificar");
        jBModificarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarOrigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOrigenLayout = new javax.swing.GroupLayout(jPOrigen);
        jPOrigen.setLayout(jPOrigenLayout);
        jPOrigenLayout.setHorizontalGroup(
            jPOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOrigenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCDestino, 0, 484, Short.MAX_VALUE)
                    .addComponent(jCOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOrigenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBModificarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPOrigenLayout.setVerticalGroup(
            jPOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOrigenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jBModificarOrigen)
                .addGap(24, 24, 24))
        );

        jPAdministrar.setOpaque(false);
        jPAdministrar.setRequestFocusEnabled(false);

        jCAlojamiento.setBackground(new java.awt.Color(209, 237, 251));
        jCAlojamiento.setForeground(new java.awt.Color(0, 0, 0));
        jCAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAlojamientoActionPerformed(evt);
            }
        });

        jLabel3.setText("Alojamiento");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(209, 237, 251));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Servicio");

        jDEntrada.setBackground(new java.awt.Color(209, 237, 251));
        jDEntrada.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setText("Entrada");

        jDSalida.setBackground(new java.awt.Color(209, 237, 251));
        jDSalida.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setText("Salida");

        jBModificarAlojamiento.setBackground(new java.awt.Color(209, 237, 251));
        jBModificarAlojamiento.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        jBModificarAlojamiento.setForeground(new java.awt.Color(0, 0, 0));
        jBModificarAlojamiento.setText("Modificar");
        jBModificarAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarAlojamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAdministrarLayout = new javax.swing.GroupLayout(jPAdministrar);
        jPAdministrar.setLayout(jPAdministrarLayout);
        jPAdministrarLayout.setHorizontalGroup(
            jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAdministrarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPAdministrarLayout.createSequentialGroup()
                        .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                            .addComponent(jCAlojamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPAdministrarLayout.createSequentialGroup()
                        .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(jDEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAdministrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBModificarAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPAdministrarLayout.setVerticalGroup(
            jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAdministrarLayout.createSequentialGroup()
                .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAdministrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPAdministrarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jCAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jBModificarAlojamiento)
                .addContainerGap())
        );

        jPPasaje.setOpaque(false);
        jPPasaje.setRequestFocusEnabled(false);
        jPPasaje.setVerifyInputWhenFocusTarget(false);

        jCPasaje.setBackground(new java.awt.Color(209, 237, 251));

        jLabel7.setText("Pasaje");

        jBModificarPasaje.setBackground(new java.awt.Color(209, 237, 251));
        jBModificarPasaje.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        jBModificarPasaje.setForeground(new java.awt.Color(0, 0, 0));
        jBModificarPasaje.setText("Modificar");
        jBModificarPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarPasajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPasajeLayout = new javax.swing.GroupLayout(jPPasaje);
        jPPasaje.setLayout(jPPasajeLayout);
        jPPasajeLayout.setHorizontalGroup(
            jPPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPasajeLayout.createSequentialGroup()
                .addGroup(jPPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPasajeLayout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(jBModificarPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPasajeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPPasajeLayout.setVerticalGroup(
            jPPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPasajeLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jBModificarPasaje)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPModificarLayout = new javax.swing.GroupLayout(jPModificar);
        jPModificar.setLayout(jPModificarLayout);
        jPModificarLayout.setHorizontalGroup(
            jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAdministrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPPasaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );
        jPModificarLayout.setVerticalGroup(
            jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPModificarLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jPAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPModificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPModificarLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.setLayer(jPModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jPModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
        );

        jDesktopPane1.setLayer(jTOrigen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTDestino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTAlojamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTPasaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jROrigen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRAlojamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRPasaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBGuardarCambios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBBorrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jCNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPasaje, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTAlojamiento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jTOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jROrigen)
                            .addComponent(jRAlojamiento)
                            .addComponent(jRPasaje)
                            .addComponent(jRNombre)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jBGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSalir)
                        .addGap(45, 45, 45))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jCNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jROrigen))
                    .addComponent(jTOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRAlojamiento)
                    .addComponent(jTAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRPasaje))
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardarCambios)
                    .addComponent(jBBorrar)
                    .addComponent(jBSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTOrigenActionPerformed

    private void jTDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDestinoActionPerformed

    private void jBGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarCambiosActionPerformed
        Paquete paquete = (Paquete) jCNombre.getSelectedItem();
        PaqueteData paqueteData = new PaqueteData();
        CiudadData ciudadData = new CiudadData();
        AlojamientoData alojamientoData = new AlojamientoData();
        PasajeData pasajeData = new PasajeData();
        paquete.setAlojamiento(alojamientoData.buscarAlojamiento(idAlojamiento));
        if(idCiudadDestino!=idCiudadOrigen){
        paquete.setDestino(ciudadData.buscarCiudad(idCiudadDestino));
        paquete.setOrigen(ciudadData.buscarCiudad(idCiudadOrigen));
        }else{
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Esta por cambiar adonde la ciudad es la misma, desea continuar?",
                    "Confirmar guardado.",
                    JOptionPane.YES_NO_OPTION
                    );
            if(confirm !=JOptionPane.YES_OPTION){
                return;
            }
        }
        paquete.setPasaje(pasajeData.buscarPasaje(idPasaje));
        if(fechaEnt!=fechaEntOriginal || fechaSal!=fechaSalOriginal){
            Alojamiento alojamiento = paquete.getAlojamiento();
            
            Alojamiento alojamientoNuevo = new Alojamiento();
            alojamientoNuevo.setCiudad(alojamiento.getCiudad());
            alojamientoNuevo.setEstado(true);
            alojamientoNuevo.setImporteDiario(alojamiento.getImporteDiario());
            alojamientoNuevo.setServicio(alojamiento.getServicio());
            alojamientoNuevo.setFechaFin(fechaSal);
            alojamientoNuevo.setFechaInicio(fechaEnt);
            alojamientoData.agregarAlojamiento(alojamientoNuevo);
        }
        paqueteData.modificarPaquete(paquete);
    }//GEN-LAST:event_jBGuardarCambiosActionPerformed

    private void jROrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jROrigenActionPerformed
       jPOrigen.setVisible(true);
       jPPasaje.setVisible(false);
       jPAdministrar.setVisible(false);
       jTNombre.setEditable(false);
       listarOrigen();
       listarDestino();
    }//GEN-LAST:event_jROrigenActionPerformed

    private void jRAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAlojamientoActionPerformed
       jPOrigen.setVisible(false);
       jPPasaje.setVisible(false);
       jPAdministrar.setVisible(true);
       jTNombre.setEditable(false);
       listaAlojamiento();
    }//GEN-LAST:event_jRAlojamientoActionPerformed

    private void jRPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRPasajeActionPerformed
       jPOrigen.setVisible(false);
       jPPasaje.setVisible(true);
       jPAdministrar.setVisible(false);
       jTNombre.setEditable(false);
       listarPasaje();
    }//GEN-LAST:event_jRPasajeActionPerformed

    private void jRNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNombreActionPerformed
       jPOrigen.setVisible(false);
       jPPasaje.setVisible(false);
       jPAdministrar.setVisible(false);
       jTNombre.setEditable(true);
    }//GEN-LAST:event_jRNombreActionPerformed

    private void jTNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNombreMouseClicked
        if(jRNombre.isSelected()){
            jTNombre.setText("");
        }
    }//GEN-LAST:event_jTNombreMouseClicked

    private void jCNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCNombreMouseEntered
        refrescarListaPaquete();
    }//GEN-LAST:event_jCNombreMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            jROrigen.setSelected(false);
            jRNombre.setSelected(false);
            jRAlojamiento.setSelected(false);
            jRPasaje.setSelected(false);
        
            jPOrigen.setVisible(false);
            jPPasaje.setVisible(false);
            jPAdministrar.setVisible(false);
            jTNombre.setEditable(false);
            
            primeraVez=0;
            
            Paquete paquete = (Paquete) jCNombre.getSelectedItem();
            //Ciudad           
            idCiudadOrigen=paquete.getOrigen().getIdCiudad();
            idCiudadDestino=paquete.getDestino().getIdCiudad();
            jTOrigen.setText(paquete.getOrigen().toString());
            jTDestino.setText(paquete.getDestino().toString());
            //Alojamiento
            idAlojamiento = paquete.getAlojamiento().getIdAlojamiento();
            double importeAlojamiento = paquete.getAlojamiento().getImporteDiario();
            fechaEnt = paquete.getAlojamiento().getFechaInicio();
            fechaSal = paquete.getAlojamiento().getFechaFin();
            String alojamiento = "ID: "+idAlojamiento + " Coste Diario: " + importeAlojamiento + " Fecha: " + fechaEnt +" - "+fechaSal;
            jTAlojamiento.setText(alojamiento);
            //Pasaje
            idPasaje = paquete.getPasaje().getIdPasaje();
            String tipo = paquete.getPasaje().getTipoTransporte();
            double importePasaje = paquete.getPasaje().getImporte();
            String pasaje = "ID: " + idPasaje + " Tipo De Transporte: "+tipo+" Coste Ida y Vuelta: "+importePasaje*2;
            jTPasaje.setText(pasaje);
            //Nombre
            jTNombre.setText(paquete.getNombre());
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBModificarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarOrigenActionPerformed
        Paquete paquete = (Paquete) jCNombre.getSelectedItem();
        Ciudad destino = (Ciudad) jCDestino.getSelectedItem();
        Ciudad origen = (Ciudad) jCOrigen.getSelectedItem();
        paquete.setDestino(destino);
        paquete.setOrigen(origen);
        idCiudadDestino=destino.getIdCiudad();
        idCiudadOrigen=origen.getIdCiudad();
        jTOrigen.setText(paquete.getOrigen().toString());
        jTDestino.setText(paquete.getDestino().toString());
    }//GEN-LAST:event_jBModificarOrigenActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();       
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jCAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAlojamientoActionPerformed
        if(jCAlojamiento.getSelectedItem()==null){
            return;
        }
        Alojamiento alojamiento = (Alojamiento) jCAlojamiento.getSelectedItem();
        jTextArea1.setText(alojamiento.getServicio());
        Date fechaEnt = Date.from(alojamiento.getFechaInicio().atStartOfDay(ZoneId.systemDefault()).toInstant());//Done
        Date fechaSal = Date.from(alojamiento.getFechaFin().atStartOfDay(ZoneId.systemDefault()).toInstant());
        jDEntrada.setDate(fechaEnt);
        jDSalida.setDate(fechaSal);
    }//GEN-LAST:event_jCAlojamientoActionPerformed

    private void jBModificarAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarAlojamientoActionPerformed
        Paquete paquete = (Paquete) jCNombre.getSelectedItem();
        Alojamiento alojamiento = (Alojamiento) jCAlojamiento.getSelectedItem();
        
        if(primeraVez==0){
            fechaEntOriginal = alojamiento.getFechaInicio();
            fechaSalOriginal = alojamiento.getFechaFin();
            primeraVez=1;
        }        
        //Dias
        fechaEnt = jDEntrada.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        fechaSal = jDSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        //Fin de dias
        int comparar = fechaEnt.compareTo(fechaSal);//Si fechaSal>fechaEnt -1
        int compararFechaEnt = fechaEntOriginal.compareTo(fechaEnt);//Si FechaEntOriginal<fechalEnt -1
        int compararFechaSal = fechaSal.compareTo(fechaSalOriginal);//Si fechaSal>fechaSalOriginal -1
        if(comparar<=0 && compararFechaEnt<=0 && compararFechaSal<=0){
            
            alojamiento.setFechaFin(fechaSal);
            alojamiento.setFechaInicio(fechaEnt);
            paquete.setAlojamiento(alojamiento);
            
            idAlojamiento = paquete.getAlojamiento().getIdAlojamiento();
            double importeAlojamiento = paquete.getAlojamiento().getImporteDiario();

            String alojamientoString = "ID: "+idAlojamiento + " Coste Diario: " + importeAlojamiento + " Fecha: " + fechaEnt +" - "+fechaSal;
            jTAlojamiento.setText(alojamientoString);
        }else{
            JOptionPane.showMessageDialog(this, "Porfavor ingrese una fecha valida.");
        }
         
    }//GEN-LAST:event_jBModificarAlojamientoActionPerformed

    private void jBModificarPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarPasajeActionPerformed
       Paquete paquete = (Paquete) jCNombre.getSelectedItem();
       Pasaje pasaje = (Pasaje) jCPasaje.getSelectedItem();
       paquete.setPasaje(pasaje);
       idPasaje = paquete.getPasaje().getIdPasaje();
            String tipo = paquete.getPasaje().getTipoTransporte();
            double importePasaje = paquete.getPasaje().getImporte();
            String pasajeString = "ID: " + idPasaje + " Tipo De Transporte: "+tipo+" Coste Ida y Vuelta: "+importePasaje*2;
            jTPasaje.setText(pasajeString);
    }//GEN-LAST:event_jBModificarPasajeActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        Paquete paquete = (Paquete) jCNombre.getSelectedItem();
        int idPaquete = paquete.getIdPaquete();
        PaqueteData paqueteData = new PaqueteData();
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Esta seguro que desea borrar este paquete?",
                "Confirmar Borrado",
                JOptionPane.YES_NO_OPTION
         );
        if(confirm==JOptionPane.YES_OPTION){
         paqueteData.borrarPaquete(idPaquete);
         refrescarListaPaquete();
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
              this.dispose();
                      this.setVisible(false); // TODO add your handling code here:

  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBGuardarCambios;
    private javax.swing.JButton jBModificarAlojamiento;
    private javax.swing.JButton jBModificarOrigen;
    private javax.swing.JButton jBModificarPasaje;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Alojamiento> jCAlojamiento;
    private javax.swing.JComboBox<Ciudad> jCDestino;
    private javax.swing.JComboBox<Paquete> jCNombre;
    private javax.swing.JComboBox<Ciudad> jCOrigen;
    private javax.swing.JComboBox<Pasaje> jCPasaje;
    private com.toedter.calendar.JDateChooser jDEntrada;
    private com.toedter.calendar.JDateChooser jDSalida;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPAdministrar;
    private javax.swing.JPanel jPModificar;
    private javax.swing.JPanel jPOrigen;
    private javax.swing.JPanel jPPasaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRAlojamiento;
    private javax.swing.JRadioButton jRNombre;
    private javax.swing.JRadioButton jROrigen;
    private javax.swing.JRadioButton jRPasaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAlojamiento;
    private javax.swing.JTextField jTDestino;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTOrigen;
    private javax.swing.JTextField jTPasaje;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
